version: '3.8'

services:
  mariadb: #healthcheck 걸기 
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    pull_policy: never
    container_name: mariadb
    restart: on-failure
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    expose: #ㅍㅣㄹ요 없지만 민정님은 썻음
      - "3306"
    networks:
      - docker-network
    #healthcheck:
    #cmd: mysqladmin ping -hlocalhost -uroot > /dev/null 2>&1
    healthcheck:
        test: [ "CMD", "mysqladmin","ping", "-hlocalhost", "-uroot"]
        start_period: 1m
        start_interval: 10s
        interval: 1m
        timeout: 5s
        retries: 3

  wordpress:
    depends_on: # 내부 옵션이 있음 - healthcheck
      - mariadb # long syntax 로 해서
    # depends_on:
    #   mariadb:
    #     condition: service_healthy
    #   redis :??? 
    #
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    pull_policy: never
    container_name: wordpress
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    expose:
      - "9000"
    networks:
      - docker-network
    # healthcheck:
    #   cmd: curl -X GET http://localhost:8080 
    #   interval: 10s

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    pull_policy: never
    container_name: nginx
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - docker-network

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jinam/data/wordpress_data
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jinam/data/mariadb_data

networks:
  docker-network:
    name: docker-network
    driver: bridge
